### ISSUE TITLE
No icon in the integration

### ISSUE THREAD

**Issue by Kreuger** [wcomartin/kia_uvo#2]
Hey man. Small issue. When adding this integration into HA, there's no current icon available. Not a big deal. Thank you for your work. I don't have an EV yet but I just wanted to test this out before getting one. Hopefully i'll be able to set this up and control it from my phone eventually so that I dont have to use the official Kia android app.

**Comment by wcomartin** [comment]
hey, I'm working on a new python lib for it, since the current lib I created only supports Canada as I come to learn afterwards, as for icons I was under the impression the icons are controlled by HA themselves? I'll look into it if not.

**Comment by alexanderwink** [comment]
Hi @wcomartin 

There is another lib available that support more regions. It's a fork based on Hyundai's BlueLink. You can find it here https://github.com/plips-nl/Kuvork

Great work made by you so far.. keep it up! 😎

**Comment by Kreuger** [comment]
I'm in Canada so I'm ok with it only working here. Haha. Let me know if you want any help. I'm looking to learn python. I've been going through some tutorial stuff learning the basics.

Edit: About the icons, I'm unsure if HA handles them as I'm new to that as well.

**Comment by olivierjag2** [comment]
kuvork works with kia car?

**Comment by alexanderwink** [comment]
Yes it's my understanding. Kuvork is a fork of BlueLink. It's basically the same service but with different URLs for KIA. Read more here https://github.com/Hacksore/bluelinky/issues/54

**Comment by olivierjag2** [comment]
i try to find how to add in home assistant, do you have idea?

**Comment by Kreuger** [comment]
@wcomartin 
I think I may have figured out why there's no icon. In your instructions, it says to copy the custom components folder however the master branch includes 2 image files. I assume they need to be copied somewhere as well? And what about the hacs.json file?

**Comment by wcomartin** [comment]
@olivierjag2 Kuvork is just a python lib for grabbing the data, the HA integration has to be built around that, I am working on that. 

@Kreuger the hacs.json file is so you can install it using the Home Assistant Community Store, https://hacs.xyz/

**Comment by Kreuger** [comment]
Yeah I wasn't aware that it was a separate thing. I have it installed now. About the icon, so you think I should include one of the two you provided somewhere and then maybe HA will see it? Maybe in the kia_uvo folder?

**Comment by wcomartin** [comment]
Are you talking about the icon in the integration page? 

If so I dont have that icon working lol. 

![image](https://user-images.githubusercontent.com/2801793/88498102-3b93be80-cf90-11ea-87ae-1d0067ec1779.png)

**Comment by Kreuger** [comment]
Yeah that's the one. I just thought maybe it would look for the icon in that folder that the rest of the script is in and since I don't have it copied there, maybe that's why it's not working.

**Comment by Kreuger** [comment]
The icons come from [here](https://github.com/home-assistant/brands). I guess you would have to submit it there.

**Comment by wcomartin** [comment]
I'm hoping that once I create the international version and refine it a bit, I can submit it to the official HA repo instead of installing it manually
